apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
    name: guestbook-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      name: guestbook-pod
  template:
    metadata:
      name: guestbook
      labels:
        app: guestbook
        name: guestbook-pod
    spec:
      containers:
        - image: kubernetes/guestbook:v2
          name: guestbook
          ports:
            - containerPort: 80
