apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: guestbook
    name: guestbook-app-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook
    name: guestbook-pod