apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
    name: guestbook-app-lb
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: guestbook
    name: guestbook-pod